import type { AttachmentCitation } from "./contracts";

const CITATION_PATTERN =
  /\u3010cite:([0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}):p(\d+):(\d+)-(\d+)\u3011/gi;
const CITATION_HREF_PATTERN =
  /^#attachment-citation:([0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}):p(\d+):(\d+)-(\d+)$/i;

function decodeCitationMatch(
  match: RegExpMatchArray,
): AttachmentCitation | null {
  const page = Number(match[2]);
  const start = Number(match[3]);
  const end = Number(match[4]);
  if (
    !Number.isSafeInteger(page) ||
    page < 1 ||
    !Number.isSafeInteger(start) ||
    start < 0 ||
    !Number.isSafeInteger(end) ||
    end <= start
  )
    return null;
  return {
    attachmentId: match[1].toLowerCase(),
    filename: "",
    page,
    start,
    end,
  };
}

/** Encode source provenance in a deliberately narrow marker for model output. */
export function citationMarker(
  citation: Omit<AttachmentCitation, "filename">,
): string {
  return `\u3010cite:${citation.attachmentId}:p${citation.page}:${citation.start}-${citation.end}\u3011`;
}

/** Convert model citation markers to safe fragment links before Markdown rendering. */
export function citationMarkersToMarkdown(
  content: string,
  filenameFor: (attachmentId: string) => string | undefined,
): string {
  return content.replace(CITATION_PATTERN, (marker, ...groups: string[]) => {
    const match = [marker, ...groups] as unknown as RegExpMatchArray;
    const citation = decodeCitationMatch(match);
    if (!citation) return marker;
    const filename = filenameFor(citation.attachmentId);
    if (!filename) return "[source unavailable]";
    const label = `${filename.replaceAll("[", "\\[").replaceAll("]", "\\]")} · p. ${citation.page}`;
    return `[${label}](#attachment-citation:${citation.attachmentId}:p${citation.page}:${citation.start}-${citation.end})`;
  });
}

/** Decode only citation fragment links generated by citationMarkersToMarkdown. */
export function citationFromHref(
  href: string | undefined,
): AttachmentCitation | null {
  const match = href?.match(CITATION_HREF_PATTERN);
  return match ? decodeCitationMatch(match) : null;
}
